### ISSUE TITLE
Piplay 1.2.50 is not 1440p

### ISSUE THREAD

**Issue by gekkehenkie11** [pimax-vr/piplay#12]
As the title says, 1.2.50 is not running at 1440p. Several users confirmed this on the forum. For me the easiest way to see is in the advanced version of VRMark, when you set rendering quality to 8k and start the 'blue room', when you look to the sign on the left, you can easily see that the quality of the letters is not as good as in 1.1.92 on 2k support (it's much easier to read on 1.1.92)

**Comment by AlienSteel** [comment]
Where did you find a version 1.2.50 of Pimax? I can only locate 1.1.92 and if searching for updates it report it's up to date.

**Comment by ghost** [comment]
try downloading here. (ch site)
http://bbs.pimaxvr.com/read.php?tid=845&fid=8 (Sign-in required)
or (Korean NAS)
http://hyunjins.dlinkddns.com:5000/sharing/m4UfgHEHs

**Comment by gekkehenkie11** [comment]
I'm closing this issue as I have another similar topic active, with more info
